import { NavDestinationShell } from '@/components/nav-destination-shell';
import { TopNav } from '@/components/top-nav';
import { getLanguage } from '@/lib/i18n';

type Props = { searchParams: { lang?: string } };

const copy = {
  es: {
    title: 'Disclaimer',
    blocks: [
      {
        type: 'paragraph' as const,
        text: 'VYM proporciona una estimación preliminar de valor basada en la información introducida por el usuario y en hipótesis definidas dentro de la herramienta.',
      },
      {
        type: 'paragraph' as const,
        text: 'No constituye asesoramiento financiero, legal, fiscal ni de inversión.',
      },
      {
        type: 'paragraph' as const,
        text: 'La información generada por VYM no sustituye una valoración independiente realizada para una transacción, litigio, proceso regulatorio o decisión formal de inversión.',
      },
    ],
  },
  en: {
    title: 'Disclaimer',
    blocks: [
      {
        type: 'paragraph' as const,
        text: 'VYM provides a preliminary value estimate based on the information entered by the user and on assumptions defined within the tool.',
      },
      {
        type: 'paragraph' as const,
        text: 'It does not constitute financial, legal, tax, or investment advice.',
      },
      {
        type: 'paragraph' as const,
        text: 'The output generated by VYM does not replace an independent valuation prepared for a transaction, dispute, regulatory process, or formal investment decision.',
      },
    ],
  },
};

export default function DisclaimerPage({ searchParams }: Props) {
  const lang = getLanguage(searchParams.lang);

  return (
    <>
      <TopNav currentPath="/disclaimer" lang={lang} />
      <NavDestinationShell blocks={copy[lang].blocks} lang={lang} title={copy[lang].title} />
    </>
  );
}
